---

  - name: Creating Filebeat Installation
    hosts: webservers
    become: true
    tasks:

    - name: Download the .deb file
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    - name: Copy the filebeat config file to the web VMs
      copy:
        src: /etc/ansible/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and configure system module
      command: metricbeat modules enable docker

    - name: Setup metricbeat
      command: metricbeat setup

    - name: Start metricbeat service
      command: metricbeat -e